apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: remindme-notifier-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - wget
            - -O
            - /dev/null
            - http://remindme-notifier:8090
          restartPolicy: OnFailure