apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: remindme-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: remindme-frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
